import React, { ReactElement, useEffect, useRef } from 'react'
import DashboardLayout from '@Components/layouts/Dashboard'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Auth from '@Pages/api/Auth'
import { Card, Container, Title } from 'ui'
import Chart from 'chart.js/auto'
import {
  FaBell,
  FaEnvelope,
  FaEllipsisV,
  FaArrowDown,
  FaArrowUp,
  FaProcedures,
  FaHospital,
  FaBed,
  FaSyringe,
  FaChevronDown,
  FaSyncAlt,
  FaSlidersH,
} from 'react-icons/fa'
import { FaUserMd } from 'react-icons/fa'
const Main = () => {
  const router = useRouter()

  const { code } = router.query
  const { getToken, getInfo } = new Auth()

  useEffect(() => {
    if (code) {
      getToken('', code)
        .then((res) => {
          console.log('token', res)
          getInfo(res.access_token)
            .then((res) => {
              console.log('user info', res)
            })
            .catch((error) => {
              console.log('error', error)
            })
        })
        .catch((error) => {
          console.log('ERROR', error)
        })
    }
  }, [code, getInfo, getToken])

  // Chart.js code to create the analytics overview chart
  // This is a placeholder and needs actual data to render the chart

  const chartRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    if (chartRef.current) {
      const ctx = chartRef.current.getContext('2d')
      if (ctx) {
        const analyticsChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: [
              'Cirugía',
              'Laboratorio',
              'Citas',
              'Doctores',
              'Pacientes',
            ],
            datasets: [
              {
                label: 'Número de Eventos',
                data: [65, 59, 80, 81, 56, 55, 40],
                fill: true,
                backgroundColor: 'rgba(75,192,192,0.2)',
                borderColor: 'rgba(75,192,192,1)',
                pointBorderColor: 'rgba(75,192,192,1)',
                pointBackgroundColor: '#fff',
                pointBorderWidth: 2,
                pointHoverRadius: 5,
                pointHoverBackgroundColor: 'rgba(75,192,192,1)',
                pointHoverBorderColor: 'rgba(220,220,220,1)',
                pointHoverBorderWidth: 2,
                pointRadius: 4,
                pointHitRadius: 10,
              },
            ],
          },
          options: {
            scales: {
              y: {
                beginAtZero: true,
              },
            },
          },
        })

        return () => {
          analyticsChart.destroy()
        }
      }
    }
  }, [])

  return (
    <>
      <Head>
        <title>Medical Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="flex w-full  bg-gradient-to-br from-blue-100 to-blue-200">
          <div className="container mx-auto  p-8 bg-white rounded-lg shadow-lg">
            <div className="flex">
              {/* <!-- Content --> */}
              <div className="w-4/5 p-4">
                <div className="flex justify-between">
                  <div className="w-1/2 ">
                    <input
                      className="p-2 border rounded w-full"
                      placeholder="Buscar aqui..."
                      type="text"
                    />
                  </div>
                  <div className="flex items-center space-x-4">
                    <FaBell className="text-yellow-500" />
                    <FaEnvelope className="text-blue-400" />
                    <FaEllipsisV className="text-gray-400" />
                  </div>
                </div>
                <h2 className="text-2xl font-bold mt-4 mb-6">Tablero</h2>
                {/* <!-- Stats Grid --> */}
                <div className="grid grid-cols-3 gap-4 mb-6">
                  {/* <!-- Doctors --> */}
                  <div className="bg-white p-6 shadow-lg rounded-lg">
                    <div className="flex items-center justify-between">
                      <div>
                        <h3 className="font-semibold text-sky-600">Doctores</h3>
                        <p className="text-xl font-bold">70</p>
                        <p className="text-sm text-gray-600">
                          Total de Doctores
                        </p>
                      </div>
                      <div className="text-sky-600">
                        <FaUserMd size={48} />
                      </div>
                    </div>
                    <div className="flex justify-between mt-2">
                      <div className="text-xs flex gap-1 items-center">
                        <FaArrowUp />
                        45
                      </div>
                      <div className="text-xs flex gap-1 items-center">
                        <FaArrowDown />
                        25
                      </div>
                    </div>
                  </div>
                  {/* <!-- Patients --> */}
                  <div className="bg-white p-6 shadow-lg rounded-lg">
                    <div className="flex items-center justify-between">
                      <div>
                        <h3 className="font-semibold text-purple-600">
                          Pacientes
                        </h3>
                        <p className="text-xl font-bold">570</p>
                        <p className="text-sm text-gray-600">
                          Total de Pacientes
                        </p>
                      </div>
                      <div className="text-purple-600">
                        <FaProcedures size={48} />
                      </div>
                    </div>
                    <div className="flex justify-between mt-2">
                      <div className="text-xs flex gap-1 items-center">
                        <FaArrowUp />
                        432
                      </div>
                      <div className="text-xs flex gap-1 items-center">
                        <FaArrowDown /> 138
                      </div>
                    </div>
                  </div>

                  {/* <!-- More Stats --> */}

                  {/* <!-- Hospital Survey --> */}
                  <div className="col-span-2 bg-white p-6 shadow-lg rounded-lg flex flex-col">
                    <div className="flex items-center justify-between mb-4">
                      <h2 className="text-xl font-bold text-blue-800">
                        Estadisticas Hospitalarias
                      </h2>
                    </div>
                    <div className="grid h-full items-center grid-cols-3 gap-4 ">
                      <div className="flex flex-col items-center text-center">
                        <FaHospital size={48} className="text-blue-600" />
                        <p className="text-xl font-bold">200</p>
                        <p className="text-sm text-gray-600">Personal Total</p>
                      </div>
                      <div className="text-center flex flex-col items-center">
                        <FaBed size={48} className="text-teal-600" />
                        <p className="text-xl font-bold">836</p>
                        <p className="text-sm text-gray-600">Número de Camas</p>
                      </div>
                      <div className="text-center flex flex-col items-center">
                        <FaSyringe size={48} className=" text-green-600" />
                        <p className="text-xl font-bold">120</p>
                        <p className="text-sm text-gray-600">
                          Cirugías Diarias
                        </p>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Balance --> */}
                  <div className="col-start-3 row-start-1 bg-white p-6 shadow-lg rounded-lg">
                    <div className="flex justify-between mb-2">
                      <h3 className="font-semibold text-xl text-red-600">
                        Balance
                      </h3>
                      <span className="text-xs text-gray-600">
                        Ultimos 7 dias
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <div>
                        <p className="text-lg font-bold text-green-600">
                          C$ 1200.00
                        </p>
                        <p className="text-sm text-gray-600">Ingresos</p>
                      </div>
                      <div>
                        <p className="text-lg font-bold text-red-600">
                          C$ 500.00
                        </p>
                        <p className="text-sm text-gray-600">Egresos</p>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Graphs and Reviews --> */}
                  {/* <!-- Analytics Overview --> */}
                  <div className="col-span-2 bg-white p-6 shadow-lg rounded-lg">
                    <div className="mb-4">
                      <h2 className="text-xl font-bold text-green-600 mb-2">
                        Análisis General
                      </h2>
                      {/* <!-- Navigation for Weekly, Monthly, Yearly --> */}
                      <div className="flex justify-between items-center mt-3">
                        <div>
                          <button className="text-sm bg-gray-200 text-gray-800 font-semibold py-2 px-4 rounded-lg mr-2">
                            Semanal
                          </button>
                          <button className="text-sm bg-blue-500 text-white font-semibold py-2 px-4 rounded-lg mr-2">
                            Mensual
                          </button>
                          <button className="text-sm bg-gray-200 text-gray-800 font-semibold py-2 px-4 rounded-lg">
                            Anual
                          </button>
                        </div>
                        <div>
                          <button className="text-gray-500">
                            <FaSlidersH />
                          </button>
                          <button className="text-green-500 ml-2">
                            <FaSyncAlt />
                          </button>
                        </div>
                      </div>
                    </div>
                    {/* <!-- Chart placeholder --> */}
                    <canvas
                      ref={chartRef}
                      id="analyticsChart"
                      className="p-4"
                    ></canvas>
                  </div>
                  {/* <!-- Reviews --> */}

                  <div className="row-start-2 col-start-3 row-span-2 max-w-sm mx-auto ">
                    {/* <!-- Reviews Section --> */}
                    <div className="bg-white p-6 rounded-lg shadow-lg">
                      <div className="flex items-center justify-between mb-4">
                        <h2 className="text-xl font-bold text-gray-800">
                          Revisiones
                        </h2>
                        <FaSyncAlt className=" text-green-500" />
                      </div>
                      {/* <!-- Placeholder for the circular progress chart --> */}
                      {/* <!-- Circular progress chart --> */}
                      <div style={{ position: 'relative' }}>
                        <svg viewBox="0 0 36 36" className="circular-chart">
                          {/* <!-- First/background circle --> */}
                          <path
                            className="circle-bg"
                            d="M18 2.0845
              a 15.9155 15.9155 0 0 1 0 31.831
              a 15.9155 15.9155 0 0 1 0 -31.831"
                          />
                          {/* <!-- Blue circle --> */}
                          <path
                            className="circle blue"
                            strokeDasharray="100, 100"
                            d="M18 2.0845
              a 15.9155 15.9155 0 0 1 0 31.831
              a 15.9155 15.9155 0 0 1 0 -31.831"
                          />
                          {/* <!-- Orange circle --> */}
                          <path
                            className="circle orange"
                            strokeDasharray="75, 100"
                            d="M18 2.0845
              a 15.9155 15.9155 0 0 1 0 31.831
              a 15.9155 15.9155 0 0 1 0 -31.831"
                            strokeLinecap="round"
                          />
                          {/* <!-- Purple circle --> */}
                          <path
                            className="circle purple"
                            strokeDasharray="25, 100"
                            d="M18 2.0845
              a 15.9155 15.9155 0 0 1 0 31.831
              a 15.9155 15.9155 0 0 1 0 -31.831"
                            strokeLinecap="round"
                          />
                        </svg>
                        <div
                          style={{
                            position: 'absolute',
                            top: '50%',
                            left: '50%',
                            transform: 'translate(-50%, -50%)',
                          }}
                        >
                          <span className="text-lg font-bold text-blue-600">
                            Standard
                          </span>
                          <span className="text-lg font-bold text-blue-600">
                            100%
                          </span>
                        </div>
                      </div>

                      {/* <!-- Follow up by department Section --> */}
                      <div className="py-6">
                        <h3 className="text-xl font-semibold text-gray-800 mb-4">
                          Seguimiento por Departamento
                        </h3>
                        <div className="space-y-4">
                          <div className="grid grid-cols-5">
                            <span className="text-sm font-medium col-span-2">
                              Laboratorio
                            </span>
                            <div className="col-span-4 progress-container">
                              <div
                                className="progress-bar"
                                style={{ width: '70%' }}
                              ></div>
                            </div>
                            <span className="text-sm font-medium ml-2">
                              70%
                            </span>
                          </div>
                          <div className="grid grid-cols-5">
                            <span className="text-sm font-medium col-span-2">
                              Cirugía
                            </span>
                            <div className="col-span-4 progress-container">
                              <div
                                className="progress-bar"
                                style={{ width: '60%' }}
                              ></div>
                            </div>
                            <span className="text-sm font-medium ml-2">
                              60%
                            </span>
                          </div>
                          <div className="grid grid-cols-5">
                            <span className="text-sm font-medium col-span-2">
                              Medicina Interna
                            </span>
                            <div className="col-span-4 progress-container">
                              <div
                                className="progress-bar"
                                style={{ width: '80%' }}
                              ></div>
                            </div>
                            <span className="text-sm font-medium ml-2">
                              80%
                            </span>
                          </div>
                          <div className="grid grid-cols-5">
                            <span className="text-sm font-medium col-span-2">
                              Ortopedia
                            </span>
                            <div className="col-span-4 progress-container">
                              <div
                                className="progress-bar"
                                style={{ width: '65%' }}
                              ></div>
                            </div>
                            <span className="text-sm font-medium ml-2">
                              65%
                            </span>
                          </div>
                          <div className="grid grid-cols-5">
                            <span className="text-sm font-medium col-span-2">
                              Pediatria
                            </span>
                            <div className="col-span-4 progress-container">
                              <div
                                className="progress-bar"
                                style={{ width: '50%' }}
                              ></div>
                            </div>
                            <span className="text-sm font-medium ml-2">
                              50%
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* <!-- Patient Satisfaction Section --> */}
                      <div className="mt-6">
                        <h3 className="text-lg font-semibold text-gray-800">
                          Satisfacción de Pacientes
                        </h3>
                        <span className="text-sm text-gray-500">
                          (% ultimo mes)
                        </span>
                        <div className="bg-gray-300 h-8 rounded-full mt-2">
                          <div
                            className="bg-teal-500 h-8 rounded-full text-right flex items-center justify-end"
                            style={{ width: '80%' }}
                          >
                            <span className="text-center text-white px-2">
                              80%
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </>
  )
}

Main.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>
}

export default Main
