import React, { ReactElement, useEffect } from 'react'
import DashboardLayout from '@Components/layouts/Dashboard'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Auth from '@Pages/api/Auth'
import { Card, Container, Title } from 'ui'

const Main = () => {
  const router = useRouter()

  const { code } = router.query
  const { getToken, getInfo } = new Auth()

  useEffect(() => {
    if (code) {
      getToken('', code)
        .then((res) => {
          console.log('token', res)
          getInfo(res.access_token)
            .then((res) => {
              console.log('user info', res)
            })
            .catch((error) => {
              console.log('error', error)
            })
        })
        .catch((error) => {
          console.log('ERROR', error)
        })
    }
  }, [code, getInfo, getToken])

  return (
    <>
      <Head>
        <title>Health App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: 'flex', width: '100%', height: '100%' }}>
        <Container>
          <Title>Bienvenido</Title>
        </Container>
      </main>
    </>
  )
}

Main.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>
}

export default Main
